apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-playground
  namespace: dev
  labels:
    app: will-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will-playground
  template:
    metadata:
      labels:
        app: will-playground
    spec:
      containers:
        - name: playground
          image: "wil42/playground:v1"
          ports:
            - containerPort: 8888
